name: Build

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/build.yml
      - cmd/**/*.go
      - makefile
      - go.mod
      - go.sum

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        goos: [windows, linux, darwin]
        arch: [amd64, arm64]
        go: ['1.20.2']

    name: "${{ matrix.platform }} | ${{ matrix.go }} | ${{ matrix.goos }} | ${{ matrix.arch }}"
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install go ${{ matrix.go }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Build
        run: |
          make OS=${{ matrix.goos }} ARCH=${{ matrix.arch }} build

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: cpackget-${{ matrix.goos }}-${{ matrix.arch }}
          path: build/cpackget*
          retention-days: 7
