name: Test

on:
  pull_request:
    paths:
      - .github/workflows/test.yml
      - cmd/**/*.go
      - testdata/**/*
      - makefile
      - .golangci.yml
      - go.mod
      - go.sum

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    timeout-minutes: 10
    strategy:
      matrix:
        platform: [ubuntu-latest]
        go: ['1.20.2']
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3

      - name: Install go ${{ matrix.go }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - uses: golangci/golangci-lint-action@v3
        with:
          # must be specified without patch version
          version: v1.51

  format:
    name: Format
    strategy:
      matrix:
        platform: [ubuntu-latest]
        go: ['1.20']
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install go ${{ matrix.go }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Check formatting
        run: |
          make format-check

  vulnerability-check:
    name: "Vulnerability check"
    strategy:
      matrix:
        platform: [ubuntu-latest]
        go: ['1.20']
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install go ${{ matrix.go }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Run vulnerability check
        run: |
          echo "$(govulncheck ./... 2>&1 | tee vulnerability_report.out)"
          test -n "$(grep 'No vulnerabilities found.' vulnerability_report.out)"

  # Make sure local_repository.pidx is linted against PackIndex.xsd
  xmllint:
    name: Xmllint
    strategy:
      matrix:
        platform: [ubuntu-latest]
        go: ['1.20']
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install go ${{ matrix.go }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Install xmllint
        run: sudo apt-get update && sudo apt-get install libxml2-utils

      - name: Check if local_repository.pidx is valid
        run: |
          make test-xmllint-localrepository

  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest]
        go: ['1.20']
    name: "${{ matrix.platform }} | ${{ matrix.go }}"
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install go ${{ matrix.go }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Unit testing
        run: |
          make coverage-check

  test-arm64:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        go: ['1.20']
        arch: [aarch64]
        distro: [ubuntu_latest]
    name: "${{ matrix.platform }} | ${{ matrix.go }} | ${{ matrix.arch }}"
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Unit testing
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
          env: |
            GIT_DISCOVERY_ACROSS_FILESYSTEM: 1
          install: |
            apt-get update -qq -y
            apt-get install -qq -y software-properties-common git make
            add-apt-repository -y ppa:longsleep/golang-backports
            apt-get update -qq -y
            apt-get install -qq -y golang-${{ matrix.go }}
          run: |
            export PATH=$PATH:/usr/lib/go-${{ matrix.go }}/bin
            git clone --depth 1 ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}
            cd cpackget
            git fetch --depth 1 origin ${GITHUB_REF}
            git checkout FETCH_HEAD
            make coverage-check
